apiVersion: apps/v1
kind: Deployment
metadata:
  name: dai-deploy
  namespace: default
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: driverlessai
    spec:
      containers:
      - name: dai-deploy
        image: h2oai/dai-centos7-x86_64:1.5.4-cuda9.0
        securityContext:
          privileged: true
        ports:
        - containerPort: 12345
          protocol: TCP
        env:
        - name: DAI_START_COMMAND
          value: "if nvidia-smi | grep -o failed || true; then ./run.sh; else nvidia-smi -pm 1 && ./run.sh; fi"
        command:
        - /bin/bash
        args:
        - -c
        - $(DAI_START_COMMAND)
        resources:
          requests:
            memory: 4Gi
            cpu: 2
            nvidia.com/gpu: 0
          limits:
            memory: 4Gi
            cpu: 2
            nvidia.com/gpu: 0
        volumeMounts:
        - mountPath: /tmp
          name: dai-deploy-pvc
        - mountPath: /log
          name: dai-deploy-pvc
      volumes:
      - name: dai-deploy-pvc
        persistentVolumeClaim:
          claimName: dai-deploy
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
