apiVersion: v1
kind: Service
metadata:
  labels:
    app: dai-deploy
  name: dai-deploy
  namespace: default
spec:
  ports:
  - port: 12345
    protocol: TCP
    targetPort: 12345
  selector:
    app: dai-deploy
  type: NodePort
  sessionAffinity: ClientIP
