apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: dai-deploy
  name: dai-deploy
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
